"use client";

import React, { useState } from "react";
import { useApp } from "@/store/AppContext";
import { Search, ArrowRight, Sparkles, MessageSquare } from "lucide-react";

const FAQ_ITEMS = [
  {
    q: "What is a carbon footprint?",
    a: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our individual actions. The average global carbon footprint for a person is about 4 tons of CO2 annually. To avoid the worst impacts of climate change, the target is to reduce this average under 2 tons by 2050."
  },
  {
    q: "How does the platform calculate my emissions?",
    a: "We multiply your activity logs (like driving distance, home electricity consumption in kWh, or diet types) by scientific conversion factors (coefficients indicating kg CO2e released per unit). These factors are updated using governmental environmental databases."
  },
  {
    q: "What are greenhouse gases?",
    a: "Greenhouse gases are atmospheric compounds (like carbon dioxide CO2, methane CH4, nitrous oxide N2O, and water vapor) that trap heat from the sun in the Earth's atmosphere, acting like a greenhouse blanket and driving global warming."
  },
  {
    q: "How do community reports create real change?",
    a: "When you report an incident like illegal dumping, the platform utilizes AI to classify the threat and assign it to the correct municipal authority. Highlighting hotspots publicly holds agencies accountable and helps NGOs organize weekend volunteer cleaning drives."
  }
];

const GUIDES = [
  { title: "Home Energy Conservation Hacks", readTime: "5 min read", category: "Electricity" },
  { title: "A Beginner's Guide to Plant-Based Eating", readTime: "7 min read", category: "Food" },
  { title: "Understanding Carbon Offsets & Credits", readTime: "6 min read", category: "Theory" },
  { title: "Urban Commuting: Transit vs Cars", readTime: "4 min read", category: "Transport" }
];

export default function LearningHubView() {
  const { setActiveTab } = useApp();
  const [searchQuery, setSearchQuery] = useState("");
  const [openFaqIdx, setOpenFaqIdx] = useState<number | null>(null);

  const filteredFaqs = FAQ_ITEMS.filter(
    (faq) => 
      faq.q.toLowerCase().includes(searchQuery.toLowerCase()) || 
      faq.a.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">Learning Hub 📖</h1>
        <p className="text-slate-500 mt-1">Explore articles on sustainability, read FAQs, or chat with our assistant.</p>
      </div>

      {/* Search Bar */}
      <div className="relative">
        <Search className="absolute left-4 top-3.5 w-5 h-5 text-slate-400" />
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Search sustainability topics, FAQs, and definitions..."
          className="w-full bg-white border border-slate-200 rounded-2xl py-3 pl-12 pr-4 outline-none text-xs font-semibold text-slate-700 shadow-sm focus:border-emerald-500"
          aria-label="Search sustainability topics, FAQs, and definitions"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* FAQs Accordion Column */}
        <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm lg:col-span-2 space-y-4">
          <h3 className="font-extrabold text-slate-800 text-sm">Frequently Asked Questions</h3>
          
          <div className="space-y-2.5">
            {filteredFaqs.map((faq, idx) => {
              const isOpen = openFaqIdx === idx;
              return (
                <div key={idx} className="border border-slate-100 rounded-xl overflow-hidden">
                  <button
                    onClick={() => setOpenFaqIdx(isOpen ? null : idx)}
                    className="w-full p-4 text-left font-bold text-xs text-slate-700 hover:text-emerald-700 flex justify-between items-center transition bg-slate-50/50"
                  >
                    <span>{faq.q}</span>
                    <span>{isOpen ? "−" : "+"}</span>
                  </button>
                  {isOpen && (
                    <div className="p-4 bg-white text-xs text-slate-500 leading-relaxed border-t border-slate-50 animate-fade-in">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}

            {filteredFaqs.length === 0 && (
              <div className="p-6 text-center text-slate-400 text-xs font-medium">
                No matching FAQ items found.
              </div>
            )}
          </div>
        </div>

        {/* Guides & Assistant Sidebar */}
        <div className="space-y-6">
          
          {/* Quick Assistant Redirect */}
          <div className="p-5 bg-emerald-600 rounded-2xl text-white shadow-md relative overflow-hidden flex flex-col justify-between h-44">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.15),transparent_60%)] pointer-events-none" />
            <div className="space-y-1.5 z-10">
              <h4 className="font-black text-sm flex items-center gap-1.5">
                <Sparkles className="w-4 h-4 fill-current" />
                <span>Ask EcoBot AI</span>
              </h4>
              <p className="text-[11px] text-emerald-100 leading-relaxed">Have custom questions about emissions, organic diets, or home composts? Ask our interactive AI helper!</p>
            </div>
            <button
              onClick={() => setActiveTab("chatbot")}
              className="mt-3 bg-white hover:bg-emerald-50 text-emerald-950 font-bold text-xs py-2 px-4 rounded-xl flex items-center justify-center gap-1.5 shadow-sm transition z-10 self-start"
            >
              <MessageSquare className="w-4 h-4" />
              <span>Start Chatting</span>
            </button>
          </div>

          {/* Reading Guides list */}
          <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm space-y-4">
            <h3 className="font-extrabold text-slate-800 text-sm">Sustainability Guides</h3>
            <div className="space-y-3">
              {GUIDES.map((guide, idx) => (
                <div key={idx} className="p-3 border border-slate-50 hover:border-emerald-100 hover:bg-emerald-50/10 rounded-xl cursor-pointer transition flex items-center justify-between gap-3 group">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800 group-hover:text-emerald-700 transition">{guide.title}</h4>
                    <div className="flex gap-2 text-[9px] text-slate-400 mt-1">
                      <span className="font-bold uppercase tracking-wider text-emerald-600">{guide.category}</span>
                      <span>•</span>
                      <span>{guide.readTime}</span>
                    </div>
                  </div>
                  <ArrowRight className="w-4 h-4 text-slate-300 group-hover:text-emerald-600 transition shrink-0" />
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
